### ISSUE TITLE
Clarify safety requirements with regard to `Safe`/`Unsafe` and data races

### ISSUE THREAD

**Issue by ghost** [rust-console/voladdress#15]
The safety requirements for `VolAddress` currently state
> Safety Invariant: The address of a VolAddress must be an aligned and legal address for a T type value (with correct R and W permissions) within the device’s memory space, otherwise the read and write methods will trigger UB when called.

Based on this safety requirement of `ptr::read_volatile` and `ptr::write_volatile`,
> Just like in C, whether an operation is volatile has no bearing whatsoever on questions involving concurrent access from multiple threads. Volatile accesses behave exactly like non-atomic accesses in that regard. In particular, a race between a write_volatile and any other operation (reading or writing) on the same location is undefined behavior.

it seems that using `Safe` for either the `R` or `W` generic parameters should also require that it is impossible to cause a data race on the address given to `VolAddress::new` by calling `VolAddress::read` or `VolAddress::write`. Is this correct and, if so, can the documentation be clarified to make this more explicit?

**Comment by Lokathor** [comment]
ah, good point. i should write that down explicitly.

**Comment by ghost** [comment]
Thinking about this more, I'm wondering what an idiomatic example of how to make a `VolAddress` safe from races would look like. My first thought was to wrap the `VolAddress` in a mutex on construction, but since `VolAddress` is `Copy`/`Clone`, safe code can still read and write outside of a lock by making a copy that outlives a mutex guard. For example, if `UART: std::sync::Mutex<VolAddress<u8, Safe, Safe>>`, two concurrent threads can still race using only safe code like
```
let uart = UART.lock().unwrap();
let v = *uart;
drop(uart);
v.write(0x5);
```

**Comment by Lokathor** [comment]
Right, if your device has more than one thread, you'd generally need to control the address usage via a value that represents ownership of the address.

However, since I largely wrote this crate for the GBA, and it's a single CPU device, then this crate doesn't bother with the synchronization element of things.

**Comment by Lokathor** [comment]
Actually, as I re-read https://llvm.org/docs/LangRef.html#volatile-memory-accesses, as well as the section just after it "Memory Model for Concurrent Operations", because VolAddress is providing volatile operations, the results of operations are not automatically a race (they're target-dependent), but also cannot be used for synchronization within the memory model.

I'll still try to fix the docs, but it'll be weirder than we first assumed.
